---
- name: Setup ZSH and basic shell config
  hosts: all
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Update cache
      become: true
      ansible.builtin.apt:
        update_cache: yes

    - name: Install packages
      become: true
      ansible.builtin.apt:
        pkg:
          - zsh
          - vim
          - mosh

    - name: ZSH Directory
      stat:
        path: ~/.oh-my-zsh
      register: omz_dir

    - name: Download Oh My ZSH installer
      ansible.builtin.command: curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -o /tmp/install.sh
      when: not omz_dir.stat.exists

    - name: Set Installer to Executable
      ansible.builtin.command: chmod +x /tmp/install.sh
      when: not omz_dir.stat.exists

    - name: Install Oh My ZSH
      ansible.builtin.command: /tmp/install.sh --unattended
      when: not omz_dir.stat.exists

    - name: Switch to ZSH shell
      become: yes
      user:
        name: "{{ the_user }}"
        shell: /usr/bin/zsh
      when: not omz_dir.stat.exists
- name: Setup github keys
  hosts: all
  tasks:
    - name: Create ssh config
      copy:
        dest: ~/.ssh/config
        content: |
          Host github.com
          Hostname github.com
          IdentityFile ~/.ssh/id_rhatfield_github
          IdentitiesOnly yes
    - name: Copy private key
      copy:
        dest: ~/.ssh/id_rhatfield_github
        src: ~/.ssh/id_rhatfield_github
